### ISSUE TITLE
Missing git tag for release 0.5.0

### ISSUE THREAD

**Issue by jirutka** [meilisearch/deserr#36]

**Comment by curquiza** [comment]
Hello @jirutka 
I think the 0.5.0 release does not exist https://github.com/meilisearch/deserr/releases

**Comment by jirutka** [comment]
So why it’s on crates.io? https://crates.io/crates/deserr/0.5.0

**Comment by curquiza** [comment]
Hum, good point, probably an issue on our side! Thank you!

@irevoire, can you fix this? Remove the crate tag or add the one on github?

**Comment by irevoire** [comment]
Hey, I pushed the tag on GitHub.

https://github.com/meilisearch/deserr/releases/tag/v0.5.0
